public class ListDemo {

    public static void listf(){
        Map<Integer,String> a=new Map<Integer,String>();
        a.put(1, 'uday');
        System.debug('size is '+a);
        /*Set<Integer> b=new Set<Integer>();
        b.add(1);
        b.add(1);
        System.debug('size is '+b.size());
      /*  List<Integer> a =new List<Integer>();
        a.add(1);
        a.add(2);
        List<Integer> b=new List<Integer>();
        b=a.clone();
        for(Integer i:b)
        {
            System.debug(i+2);
        }
        System.debug('size is '+b.size());
        System.debug('size is '+b.size());*/
    }
}